# Generated by Django 2.2.3 on 2019-08-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalapi', '0004_auto_20190818_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='protocol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portalapi.Protocol'),
        ),
    ]
