# Generated by Django 2.2.3 on 2019-08-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portalapi', '0005_auto_20190818_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalquestions',
            name='question_types',
            field=models.CharField(choices=[('PO', 'Polar'), ('OP', 'Options')], default='PO', max_length=2),
        ),
    ]
