# Generated by Django 2.2.3 on 2019-08-17 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portalapi', '0006_medicalquestions_question_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalquestions',
            old_name='question_types',
            new_name='question_type',
        ),
    ]
