# Generated by Django 2.2.3 on 2019-08-19 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalapi', '0007_auto_20190818_0426'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAnswers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapi.Patient')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapi.MedicalQuestions')),
            ],
        ),
    ]
