# Generated by Django 2.2.3 on 2019-09-20 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalapi', '0010_auto_20190825_0344'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalQuestionChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portalapi.MedicalQuestions')),
            ],
        ),
    ]
