# Generated by Django 2.2.3 on 2019-09-20 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portalapi', '0011_medicalquestionchoices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalquestionchoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='portalapi.MedicalQuestions'),
        ),
    ]
