export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_USER = "LOGOUT_USER";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAIL = "SIGNUP_FAIL";

export const PATIENT_REGISTER_SUCCESS = "PATIENT_REGISTER_SUCCESS";
export const PATIENT_REGISTER_FAIL = "PATIENT_REGISTER_FAIL";
export const GET_PATIENTS = "GET_PATIENTS";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const ADD_PATIENT = "ADD_PATIENT"; 
export const PATIENT_LOADING = "PATIENT_LOADING"; 

export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const GET_PROTOCOLS = "GET_PROTOCOLS";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const QUESTIONS_LOADING = "QUESTIONS_LOADING";
export const UPDATE_QUESTION = "UPDATE_QUESTION";
export const POST_QUESTION = "POST_QUESTION";
export const POST_QUESTION_FAILED = "POST_QUESTION_FAILED"
